from flask import Flask, request, jsonify
from flask_cors import CORS
import whisper
import tempfile
import os
import requests

app = Flask(__name__)
CORS(app)

model = whisper.load_model("base")
url = "http://localhost:3000/chat"

@app.route('/upload', methods=['POST'])
def upload_audio():
    if 'audio' not in request.files:
        return jsonify({'error': 'No file uploaded'}), 400

    audio_file = request.files['audio']
    
    # TEMP FILE FIX FOR WINDOWS
    with tempfile.NamedTemporaryFile(suffix=".webm", delete=False) as temp_audio:
        temp_filename = temp_audio.name
    try:
        audio_file.save(temp_filename)
        result = model.transcribe(temp_filename)
        requests.post(url,json={'transcript': result['text']}) #sending the text generated by the whisper to LLM 
        return jsonify({'transcript': result['text']})
    finally:
        os.remove(temp_filename)

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)